const planetsList = [
	"Snafu",
	"Chopin",
	"Melthorne",
	"Bed Rock",
	"Siren",
	"Tao",
	"Status",
	"Deneb",
	"Vega",
	"Fugue",
	"Senility",
	"Saturn",
	"Sand Castle",
	"Texas",
	"Beauregard",
	"Spaatz",
	"Deacon",
	"Rake",
	"Sad",
	"Crow",
	"Harding",
	"Pin Prick",
	"Tangent",
	"Vox",
	"Ruby",
	"Scat",
	"Challenger",
	"Utopia",
	"Puma",
	"Neuter",
	"Phicol",
	"Sands Of Time",
	"Nessus",
	"Dachshund",
	"Alpha Centauri",
	"Canis Minor",
	"Pyxidis",
	"Marion",
	"Johnson",
	"Beacon",
	"MacArthur",
	"Happy",
	"Dive",
	"Canterbury",
	"Revelation",
	"Chubs",
	"Marge",
	"Tanj",
	"Match",
	"Tongue",
	"PCP",
	"Pisces",
	"Prune",
	"Blossom",
	"Carcassonne",
	"Boethius",
	"Arafat",
	"Stuart",
	"Waco",
	"Hydra",
	"Skink",
	"Yank",
	"Daisy",
	"Shaft",
	"Grape",
	"Boron",
	"Bath",
	"Cathlamet",
	"Finger",
	"Blush",
	"Leo Minor",
	"Stilton",
	"Pickles",
	"Purgatory",
	"Penance",
	"Garlic",
	"Curley",
	"Down And Out",
	"Never Never Land",
	"LGM 4",
	"Mustang",
	"Grep",
	"Mozart",
	"Chunk",
	"Bountiful",
	"True Faith",
	"Halsey",
	"Aurora",
	"Redemption",
	"Wanker's Corner",
	"Charity",
	"Afterthought",
	"Crabby",
	"Smorgasbord",
	"Winkle",
	"Shoe Shine",
	"Trurl",
	"Armstrong",
	"Carbon",
	"Buckshot",
	"Puss Puss",
	"Equuleus",
	"Kulu",
	"Silicon",
	"Doodles",
	"Trog",
	"Kumquat",
	"Clover",
	"Forrest",
	"Hedtke",
	"Almagest",
	"Pluto",
	"Split",
	"Excel",
	"Peat Moss",
	"Ditto",
	"Pound",
	"Last Chance",
	"Taco",
	"Moonbeam",
	"Marla",
	"Chandrasekhar",
	"Zeta",
	"Bagnose",
	"April",
	"Strauss",
	"Silver",
	"Sequim 3",
	"LGM 2",
	"Dewey",
	"Larry",
	"Skid Row",
	"Grouse",
	"Zucchini",
	"Poly Gone",
	"Tank Top",
	"Eisenhower",
	"Recalc",
	"Relight",
	"Floyd",
	"Eridanus",
	"Homogeneous",
	"Iodine",
	"Ursa Good",
	"Nitrogen",
	"Devo",
	"Wagner",
	"Omega",
	"Kutuzov",
	"Crux",
	"Mitchell",
	"Callipus",
	"Philistia",
	"Goober",
	"Tweedledee",
	"Cramp",
	"Nylon",
	"Knob",
	"Celery",
	"Darien",
	"Hal",
	"Phi",
	"Carter",
	"Allenby",
	"Gaye",
	"Bob",
	"Axelrod",
	"Hydrogen",
	"Jerilyn",
	"90210",
	"Graz",
	"Flint Stone",
	"Amontillado",
	"Yoruba",
	"Baker",
	"Roosevelt",
	"Cinnamon",
	"Zahir",
	"Nod",
	"Oxygen",
	"Discovery",
	"Dunsany",
	"Eno",
	"Simple",
	"Meade",
	"Bakwele",
	"Montgomery",
	"H2O",
	"Ursa Major",
	"Spearmint",
	"Buttercup",
	"Caelum",
	"Chamber",
	"Skidmark",
	"Vanilla",
	"Putty",
	"Tartaruga",
	"Radian",
	"Utgard",
	"Talking Desert",
	"Rhenium",
	"Birthmark",
	"Bach",
	"Resistor",
	"Carver",
	"Flutter Valve",
	"Love",
	"Stellar",
	"Nirvana",
	"America",
	"Beethoven",
	"Pi",
	"Icarus",
	"Elephant Ear",
	"Squidcakes",
	"Bog",
	"Diablo",
	"Snuffles",
	"Lynx",
	"Triffid",
	"Escalator",
	"Lee",
	"Pitstop",
	"Black Hole",
	"Kirk",
	"Dwarte",
	"Valhalla",
	"Lithium",
	"Leo",
	"Kosciusko",
	"Ursa Minor",
	"Serapa",
	"Gout",
	"Wobegon",
	"Desolate",
	"Kruger",
	"Almighty",
	"Wendy",
	"Estes",
	"Zanzibar",
	"Shaggy Dog",
	"Beautiful",
	"Mana",
	"No Return",
	"Scandahoovia",
	"Thomas",
	"Red Storm",
	"Guano",
	"Gertrude",
	"Cirrus",
	"Latte",
	"Wallaby",
	"Prydun",
	"Planet 10",
	"Hoover",
	"Verdi",
	"Lizard's Beak",
	"Rock",
	"Samsonov",
	"Winter",
	"Shank",
	"Corner",
	"Zhukovi",
	"Beta",
	"Molybdenum",
	"Clark",
	"Fluorine",
	"Grey Matter",
	"Pickett",
	"Doris",
	"Dimna",
	"Shinola",
	"Springfield",
	"Jubitz",
	"Milky Way",
	"Mungle",
	"Zippy",
	"Evergreen",
	"Sam",
	"Denon",
	"Opus 10",
	"Rho",
	"Basket Case",
	"Memos",
	"Lycra",
	"Scorpius",
	"Me",
	"Green House",
	"Nivenyrral",
	"Replica",
	"Sadie",
	"Spruance",
	"Smithers",
	"Puberty",
	"Faith",
	"Sulfur",
	"Pinball",
	"Nastrond",
	"PiR2",
	"Red Giant",
	"Nowhere",
	"Dinky",
	"Infinity Junction",
	"Shangri-La",
	"Radish",
	"Rye",
	"Scurvy",
	"Pearl",
	"Kearny",
	"Ney",
	"Mu",
	"Cambridge",
	"Harlequin",
	"Clapton",
	"Planet 9",
	"Gas",
	"Resort",
	"Tlon",
	"Ultima Thule",
	"Shanty",
	"X-Ray",
	"Kidney",
	"Wammalammadingdong",
	"Spitfire",
	"Decatur",
	"Bladderworld",
	"Money",
	"Sed",
	"Core",
	"Braddock",
	"Marlborough",
	"Spaceball",
	"Wainwright",
	"Skloot",
	"Bonn",
	"Hammer",
	"Spittle",
	"Emperium Gate",
	"Graceland",
	"Bone",
	"Betelgeuse",
	"Raster",
	"Howe",
	"Coolidge",
	"No Exit",
	"Steeple",
	"Jersey",
	"Rough Shod",
	"Garfunkel",
	"Yes",
	"Bentley",
	"Scud",
	"Draco",
	"Hell",
	"Sparta",
	"Snake's Belly",
	"Dave",
	"Cancer",
	"Stilwell",
	"Klaupaucius",
	"Dyson",
	"Venus",
	"Foucault's World",
	"Finale",
	"Mongo",
	"Climax",
	"Mobius",
	"Custer",
	"Pilgrim's Harbor",
	"Scarlett",
	"Globular Rex",
	"Swizzle Stick",
	"Contra",
	"Kwaidan",
	"Gladsheim",
	"Presley",
	"Truck Stop",
	"Shannon",
	"Who",
	"Capricornus",
	"Rex",
	"Hunt",
	"Muspell",
	"Accord",
	"Winky-Blinky",
	"Lhasa",
	"Alsea",
	"Neil",
	"No Play",
	"Moscow",
	"Taton",
	"Mandelbrot",
	"Clatsop",
	"Captain Jack",
	"Tsagigla'lal",
	"Cochise",
	"Burrito",
	"Argon",
	"Clausewitz",
	"Early",
	"Sea Squared",
	"Wizzle",
	"Nickel",
	"Lekgolo",
	"Libra",
	"New",
	"Guderian",
	"3M TA3",
	"Esther",
	"Hoof And Mouth",
	"Ozone",
	"Saada",
	"Lever",
	"Cassiopeia",
	"Wingnut",
	"Gladiolus",
	"Kornilov",
	"Washington",
	"Dipstick",
	"Stove Top",
	"Chaos",
	"Hard Ball",
	"Joffre",
	"Catnip",
	"Planet X",
	"Epsilon",
	"Allegro",
	"Ariel",
	"Trial",
	"Inside-Out",
	"Poly Siren",
	"Same Here",
	"Sartre",
	"Blue Giant",
	"Peekaboo",
	"Bilbo",
	"Glenn",
	"Clay",
	"Chennault",
	"Cousin Louie",
	"Hiho",
	"Lambda",
	"Qaphqa",
	"La Te Da",
	"Basil",
	"Little Sister",
	"Speed Bump",
	"Cherry",
	"Ya Betcha",
	"Zed",
	"Niflheim",
	"Rundstedt",
	"Tattoo",
	"Dimple",
	"Virgo",
	"Denikin",
	"Bufu",
	"Sapphire",
	"Lachesis",
	"Gollum",
	"Hill",
	"Kennedy",
	"Hindsight",
	"Nipso",
	"Maggie",
	"Sniffles",
	"Schubert",
	"Stanley",
	"Veritas",
	"Aluminum",
	"98053",
	"Ice Patch",
	"Simon",
	"Andante",
	"Karhide",
	"Taurus",
	"H2SO4",
	"Myopus",
	"Bonus",
	"Erasmus",
	"Memmon",
	"Abdera",
	"Elder",
	"Jupiter",
	"Lopsided",
	"Yeager",
	"Tweedledum",
	"Penzance",
	"Y-Has",
	"Io",
	"Loan Shark",
	"Grim Reaper",
	"Selenium",
	"Tierra",
	"Ricketts",
	"Sagittarius",
	"Neptune",
	"Bambi",
	"Gamma",
	"Abrams",
	"Lavacious",
	"Whistler's Mother",
	"Radium",
	"Pegasus",
	"Murat",
	"Skynyrd",
	"No Respect",
                "yeoman of the guard",
                "yeoman service",
                "yeoman's service",
                "yeomen of the guard",
                "yerba buena",
                "yerba mansa",
                "yerba mate",
                "yerba reuma",
                "yerba sagrada",
                "yerba santa",
                "yerba-mate",
                "yerk out",
                "yes indeed",
                "yes indeedy",
                "yes ma'am",
                "yes man",
                "yes sir",
                "yes sirree",
                "yes-and-no answer",
                "yes-man",
                "yes-no",
                "yes-noer",
                "yes-noism",
                "yeshiva bocher",
                "yester-",
                "yester-year",
                "yesterday and today and forever",
                "yet again",
                "yew berry",
                "yew family",
                "yew green",
                "yew pine",
                "yew tree",
                "yew-besprinkled",
                "yew-crested",
                "yew-hedged",
                "yew-leaved",
                "yew-roofed",
                "yew-shaded",
                "yew-treed",
                "yi tsing ware",
                "yield a profit",
                "yield again to",
                "yield an aroma",
                "yield an odor",
                "yield assent",
                "yield hope",
                "yield point",
                "yield strength",
                "yield stress",
                "yield the floor",
                "yield the ghost",
                "yield the palm",
                "yield the spirit",
                "yield to",
                "yield to despair",
                "yield to maturity",
                "yield value",
                "yield your breath",
                "yielding a return",
                "yielding prop",
                "yill-caup",
                "ylang-ylang",
                "yo-heave-ho",
                "yo-ho",
                "yo-ho-ho",
                "yo-kyoku",
                "yo-yo",
                "yoga trance",
                "yohimbe bark",
                "yoke bone",
                "yoke devil",
                "yoke elm",
                "yoke front",
                "yoke method",
                "yoke riveter",
                "yoke with",
                "yoke-footed",
                "yoke-toed",
                "yolk bag",
                "yolk boil",
                "yolk cord",
                "yolk duct",
                "yolk gland",
                "yolk nucleus",
                "yolk plate",
                "yolk plug",
                "yolk sac",
                "yolk stalk",
                "yolk yellow",
                "yom kippur",
                "yom tob",
                "yom tobs",
                "yom tov",
                "yom tovs",
                "yomin tovim",
                "yoo-hoo",
                "york rite",
                "yorkshire pudding",
                "yorkshire terrier",
                "you and me",
                "you are mistaken",
                "you are right",
                "you are wrong",
                "you bet",
                "you bet your boots",
                "you bet your life",
                "you better believe it",
                "you can bank on it",
                "you can bet on it",
                "you can bet your bottom dollar",
                "you can just bet",
                "you can make book on it",
                "you can say that again",
                "you can't go wrong",
                "you don't say",
                "you have another guess coming",
                "you name it",
                "you said a mouthful",
                "you said it",
                "you should live so long",
                "you speak truly",
                "you too",
                "you're all wet",
                "you're darn tootin'",
                "you're not kidding",
                "you're telling me",
                "you're way off",
                "you've got it",
                "you've got me",
                "you've got something there",
                "you-all",
                "you-be-damned",
                "you-be-damnedness",
                "you-know-what",
                "you-know-who",
                "you-uns",
                "young animal",
                "young bird",
                "young blood",
                "young buck",
                "young cat",
                "young chicken",
                "young cow",
                "young creature",
                "young deer",
                "young devil",
                "young dog",
                "young duck",
                "young frog",
                "young fry",
                "young fustic",
                "young generation",
                "young goat",
                "young goose",
                "young hopeful",
                "young horse",
                "young hyson",
                "young insect",
                "young lady",
                "young man",
                "young one",
                "young people",
                "young person",
                "young pig",
                "young sheep",
                "young thing",
                "young turk",
                "young whippersnapper",
                "young woman",
                "young-bladed",
                "young-chinned",
                "young-conscienced",
                "young-counseled",
                "young-eyed",
                "young-headed",
                "young-ladydom",
                "young-ladyfied",
                "young-ladyhood",
                "young-ladyish",
                "young-ladyism",
                "young-ladylike",
                "young-ladyship",
                "young-looking",
                "young-manhood",
                "young-manlike",
                "young-manliness",
                "young-manly",
                "young-mannish",
                "young-mannishness",
                "young-manship",
                "young-old",
                "young-winged",
                "young-womanhood",
                "young-womanish",
                "young-womanishness",
                "young-womanlike",
                "young-womanly",
                "young-womanship",
                "young-yeared",
                "younger generation",
                "youngest-born",
                "your adieus",
                "your all",
                "your ancestors",
                "your applecart",
                "your best",
                "your best effort",
                "your best endeavor",
                "your betters",
                "your blind side",
                "your blood",
                "your crowd",
                "your cup of tea",
                "your days are numbered",
                "your doom is sealed",
                "your due",
                "your fathers",
                "your grain",
                "your head off",
                "your hour",
                "your hour is come",
                "your last hour",
                "your level best",
                "your native ground",
                "your native heath",
                "your native place",
                "your number is up",
                "your own choice",
                "your own discretion",
                "your own initiative",
                "your own level",
                "your own man",
                "your own will",
                "your race is run",
                "your ribs",
                "your say",
                "your set",
                "your turn",
                "your utmost",
                "your worth",
                "yours truly",
                "youth club",
                "youth group",
                "youth hood",
                "youth hostel",
                "youth hosteler",
                "youth market",
                "youth offender",
                "youth-bold",
                "youth-consuming",
                "youthful offender",
                "youthful spirits",
                "ytterbium metal",
                "ytterbium oxide",
                "yttrium metal",
                "yttrium oxide",
                "yttro-",
                "yuan dollar",
                "yucca borer",
                "yucca cactus",
                "yucca fertilizer",
                "yucca moth",
                "yucca palm",
                "yucca pollenizer",
                "yuk-yuk",
                "yukon time",
                "yule block",
                "yule clog",
                "yule log",
                "yum-yum",
                "z iron",
                "z term",
                "z-axes",
                "z-axis",
                "zB",
                "zZt",
                "za-zen",
                "zacate limon",
                "zanona palm",
                "zante fustic",
                "zapota gum",
                "zeal-blind",
                "zeal-consuming",
                "zeal-inflamed",
                "zeal-inspiring",
                "zeal-pretending",
                "zeal-quenching",
                "zeal-scoffing",
                "zeal-transported",
                "zeal-worthy",
                "zebra antelope",
                "zebra bird",
                "zebra caterpillar",
                "zebra crossing",
                "zebra finch",
                "zebra fish",
                "zebra grass",
                "zebra opossum",
                "zebra parakeet",
                "zebra plant",
                "zebra poison",
                "zebra shark",
                "zebra spider",
                "zebra swallowtail",
                "zebra wolf",
                "zebra-back",
                "zebra-plant",
                "zebra-tailed",
                "zebra-tailed lizard",
                "zebrawood family",
                "zebu cattle",
                "zee bar",
                "zeeman effect",
                "zenaida dove",
                "zend-avesta",
                "zenith blue",
                "zenith collimator",
                "zenith distance",
                "zenith point",
                "zenith sector",
                "zenith star",
                "zenith telescope",
                "zenith tube",
                "zenith-pole",
                "zenith-pole arc",
                "zenith-star arc",
                "zenithal projection",
                "zephr worsted",
                "zephyr cloth",
                "zephyr flower",
                "zephyr lily",
                "zephyr shawl",
                "zephyr shirting",
                "zephyr worsted",
                "zephyr yarn",
                "zephyr-fanned",
                "zephyr-haunted",
                "zephyr-kissed",
                "zero ablaut grade",
                "zero algebra",
                "zero beat",
                "zero day",
                "zero element",
                "zero fleck",
                "zero grade",
                "zero gravity",
                "zero grazing",
                "zero group",
                "zero hour",
                "zero in",
                "zero in on",
                "zero magnet",
                "zero mark",
                "zero matrix",
                "zero method",
                "zero oil",
                "zero point",
                "zero post",
                "zero potential",
                "zero set",
                "zero stage",
                "zero stem",
                "zero thrust pitch",
                "zero tone",
                "zero torque pitch",
                "zero vector",
                "zero weather",
                "zero-dimensional",
                "zero-divisor",
                "zero-lift",
                "zero-lift angle",
                "zero-point energy",
                "zero-rated",
                "zero-thrust pitch",
                "zero-zero",
                "zeroth law of thermodynamics",
                "zeta function",
                "zetetic philosophy",
                "zig and zag",
                "zigzag course",
                "zigzag fence",
                "zigzag path",
                "zigzag rule",
                "zigzag-fashion",
                "zigzag-lined",
                "zigzag-shaped",
                "zila parishad",
                "zimocca sponge",
                "zinc alkyl",
                "zinc amide",
                "zinc blende",
                "zinc bloom",
                "zinc bromide",
                "zinc carbonate",
                "zinc chloride",
                "zinc chromate",
                "zinc chrome",
                "zinc crust",
                "zinc dust",
                "zinc engraving",
                "zinc etching",
                "zinc ethide",
                "zinc ethyl",
                "zinc fixer",
                "zinc flowers",
                "zinc gray",
                "zinc green",
                "zinc methide",
                "zinc methyl",
                "zinc ointment",
                "zinc orange",
                "zinc oxide",
                "zinc phosphide",
                "zinc sender",
                "zinc spar",
                "zinc spinel",
                "zinc standard cell",
                "zinc stearate",
                "zinc sulfate",
                "zinc sulfide",
                "zinc sulphate",
                "zinc sulphide",
                "zinc vitriol",
                "zinc white",
                "zinc yellow",
                "zinc-coated",
                "zinc-etched",
                "zinc-lined",
                "zinc-roofed",
                "zinc-sampler",
                "zinco-",
                "zinco-polar",
                "zip code",
                "zip fastener",
                "zip gun",
                "zip through",
                "zip up",
                "zircon lamp",
                "zircon light",
                "zircon-syenite",
                "zirconium dioxide",
                "zirconium oxide",
                "zo-",
                "zodiacal constellation",
                "zodiacal light",
                "zona pellucida",
                "zonae pellucidae",
                "zonal soil",
                "zone axis",
                "zone catalogue",
                "zone fire",
                "zone line",
                "zone melting",
                "zone of communications",
                "zone of fire",
                "zone of interior",
                "zone of no signal",
                "zone phenomenon",
                "zone plate",
                "zone refining",
                "zone system",
                "zone tariff",
                "zone time",
                "zone-confounding",
                "zone-marked",
                "zone-tailed",
                "zoning act",
                "zoning commission",
                "zoning law",
                "zoning laws",
                "zoning ordinance",
                "zonked out",
                "zono-",
                "zoo-",
                "zoo-ecologist",
                "zoo-ecology",
                "zoogenic infection",
                "zoological garden",
                "zoom binoculars",
                "zoom in",
                "zoom lens",
                "zoom shot",
                "zoot suit",
                "zoot-suiter",
                "zwitter ion",
                "zyg-",
                "zygo-",
                "zygomatic arch",
                "zygomatic bone",
                "zygomatic process",
                "zym-",
                "zymo-",
];
